#注意事项：冒号之后一定要有一个空格！！！ 切记-这个是yaml的语法格式
LoginPage: #登录页面
  username_input: ["css selector", '[placeholder= "请输入用户名"]'] # 账号输入框
  pwd_input: ["css selector", '[placeholder= "请输入密码"]'] # 密码输入框
  codepic : ["css selector", "button span> img"] # 验证码图片地址
  code : ["css selector", '[placeholder= "请输入验证码"]'] # 验证码输入框
  login_btn: ["css selector", "button.ivu-btn-primary"] # 登录按钮

MainPage: #选择主菜单
  dashboard: ['css selector','ul.ivu-menu-horizontal a:nth-child(1)']  #工作台
  task: ['css selector','ul.ivu-menu-horizontal a:nth-child(2)'] # 我的工作
  service: ['css selector','ul.ivu-menu-horizontal a:nth-child(3)'] # 服务中心
  resource: ['css selector','ul.ivu-menu-horizontal a:nth-child(4)'] # 资源管理
  system: ['css selector','ul.ivu-menu-horizontal a:nth-child(5)'] # 系统管理
  message: ['css selector','ul.ivu-menu-horizontal a:nth-child(6)'] # 系统管理


Mytask: #绑定火运计划页面
    pending: "http://hn.sjbs.360unicom.cn/work/task/pending" #我的代办
    finished: "http://hn.sjbs.360unicom.cn/work/task/finished" # 我的已办
    distribute: "http://hn.sjbs.360unicom.cn/work/task/distribute" # 我的分发
    approval: "http://hn.sjbs.360unicom.cn/work/task/approval" # 待我审批
    has_approval: "http://hn.sjbs.360unicom.cn/work/task/has-approved" # 我的已审

Handletask:
    handle: ["css selector",".ivu-card-body tbody .ivu-table-row .action-edit"]


